// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAuNpe8nIdBgGAawAdtbPxuYptfIHW-IeA',
    appId: '1:141558018210:web:c3bd761d8848a2033f67fb',
    messagingSenderId: '141558018210',
    projectId: 'technopalette-test',
    authDomain: 'technopalette-test.firebaseapp.com',
    storageBucket: 'technopalette-test.firebasestorage.app',
    measurementId: 'G-JXG2QEP2G3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWxBdl1UJMi0gZx8m67GgpsyD9s2p2aNc',
    appId: '1:141558018210:android:f5922420ab9fcf033f67fb',
    messagingSenderId: '141558018210',
    projectId: 'technopalette-test',
    storageBucket: 'technopalette-test.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB739DqTaMNkauOUQV8PUd9i8eCZqhQkO0',
    appId: '1:141558018210:ios:2c0b3b2111d1f02c3f67fb',
    messagingSenderId: '141558018210',
    projectId: 'technopalette-test',
    storageBucket: 'technopalette-test.firebasestorage.app',
    iosBundleId: 'com.example.technopaletteMachineTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB739DqTaMNkauOUQV8PUd9i8eCZqhQkO0',
    appId: '1:141558018210:ios:2c0b3b2111d1f02c3f67fb',
    messagingSenderId: '141558018210',
    projectId: 'technopalette-test',
    storageBucket: 'technopalette-test.firebasestorage.app',
    iosBundleId: 'com.example.technopaletteMachineTest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAuNpe8nIdBgGAawAdtbPxuYptfIHW-IeA',
    appId: '1:141558018210:web:f540b7a130cc32c83f67fb',
    messagingSenderId: '141558018210',
    projectId: 'technopalette-test',
    authDomain: 'technopalette-test.firebaseapp.com',
    storageBucket: 'technopalette-test.firebasestorage.app',
    measurementId: 'G-SE8WXFX6F5',
  );
}
